testRunTime: testRunTime.cpp BinaryHeap.cpp BinomialHeap.cpp
	g++ -std=c++11 -o testRunTime testRunTime.cpp BinaryHeap.cpp BinomialHeap.cpp
testBinomial: testBinomialHeap.cpp BinaryHeap.cpp BinomialHeap.cpp
	g++ -std=c++11 -o testBinomial testBinomialHeap.cpp BinaryHeap.cpp BinomialHeap.cpp
